# config file
title: Daily Developer Jokes
description: New dev jokes and programming humor every day.
short_description: Developer jokes posted daily.
author: Gabriel Romualdo
author_url: https://xtrp.io/
submit_url: https://forms.gle/qdgaex9waNp4cLzW7
blog_post: https://xtrp.io/blog/2020/01/12/daily-jokes-bot-release/
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://dailydeveloperjokes.github.io/' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

# pagination
paginate: 10
paginate_path: '/page/:num/'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
